// Generated by Copilot, modified by me
import L from 'leaflet';
import { computed, type Ref } from 'vue';
import { BoundingBox, BoundsSelector } from '@/types';
import { useBounds } from './useBounds';

export function useLeafletBounds(
  date: Ref<Date>,
  customSelector?: BoundsSelector
) {
  // Get the library-agnostic bounds
  const { currentBounds, boundsArray, boundsCollection } = useBounds(date, customSelector);

  // Helper function to convert any BoundingBox to Leaflet bounds
  function toLeafletBounds(boundingBox: BoundingBox): L.LatLngBounds {
    return new L.LatLngBounds(
      new L.LatLng(boundingBox.south, boundingBox.west),
      new L.LatLng(boundingBox.north, boundingBox.east)
    );
  }

  // Convert to Leaflet LatLngBounds
  const leafletBounds = computed(() => {
    return toLeafletBounds(currentBounds.value);
  });

  return {
    boundsCollection,
    currentBounds,
    boundsArray,
    leafletBounds,
    toLeafletBounds
  };
}